#!/bin/bash
source ./utils.sh

qrcode() {
  local model="$1"
  local size="$2"
  local data="$3"

  # QR Code Commands
  echo -ne "\x1D\x28\x6B\x03\x00\x31\x41${model}"  # Set QR code model
  echo -ne "\x1D\x28\x6B\x03\x00\x31\x43${size}"   # Set QR code size
  echo -ne "\x1D\x28\x6B\x03\x00\x31\x45\x31"      # Set error correction (medium)

  local length=$(printf '\x%02X' $((${#data}+3)))  # Calculate length of data
  echo -ne "\x1D\x28\x6B${length}\x00\x31\x50\x30${data}"  # Store data
  echo -ne '\x1D\x28\x6B\x03\x00\x31\x51\x30'      # Print the QR code
}
